INSERT INTO items (id, title, description, image, available, user_id)
VALUES
  (1, 'Sami et Julie à la plage',
    'Munis de leur seau, de leur pelle et leurs brassards, Sami et Julie vont passer un bel après-midi à la plage! Cette collection de lecture à deux voix, dans laquelle l’adulte lit le texte et l’enfant nomme les mots illustrés, permet à votre enfant de structurer son langage, de se préparer à l’apprentissage de la lecture, et de comprendre ses propres émotions grâce à des thèmes qui lui sont familiers. Des petites histoires qui font parler les enfants! ', 'https://images-na.ssl-images-amazon.com/images/I/51Griyx+2dL._SX437_BO1,204,203,200_.jpg', TRUE, 2),
  (2, 'Le petit Chaperon rouge',
    'Un livre pour entrer dans la lecture dès la maternelle - les digrammes sont en vert pour signaler les paires de lettres qui produisent un son. - les lettres muettes sont en gris pour repérer les lettres qui ne se prononcent pas. - des capitales pour faciliter la reconnaissance des lettres. - des bulles pour désigner qui parle. - des onomatopées pour un premier niveau de lecture très simple. Dès que l’enfant connaît le son des lettres et des principaux digrammes (OU, AN, ON…), il peut lire son premier livre !', 'https://images-na.ssl-images-amazon.com/images/I/41jk5sDc57L._SX412_BO1,204,203,200_.jpg', FALSE, 3),
  (3, 'Le grand imagier de la nature',
    'Un somptueux imagier pour goûter au plaisir de la découverte de la nature, une merveilleuse encyclopédie visuelle de la nature.Plus de 600 images choisies et ordonnées par des spécialistes afin de répondre à la curiosité insatiable des enfants.', 'https://images-na.ssl-images-amazon.com/images/I/51zSw0xiTZL._SX391_BO1,204,203,200_.jpg', TRUE, 2),
  (4, 'Ludanimo',
    'Trois jeux pour les tout-petits Jeu de memo Jeu d équilibre Jeu de parcours A partir de 3 ans De 1 à 4 joueurs', 'https://images-na.ssl-images-amazon.com/images/I/411Zy3sfj2L._SX432_BO1,204,203,200_.jpg', FALSE, 1),
  (5, 'Mon amour',
    'Sur chaque double page, Astrid Desbordes a choisi d opposer en vis-à-vis des situations contraires, qui jouent avec aisance sur les registres du quotidien et de l imaginaire, de la poésie et de l humour. Le message de cet irrésistible album est simple et limpide : l amour est constant et sans condition. Mais c est dans la toute dernière phrase que se cache le véritable secret : « Je t aime parce que tu es mon enfant / mais que tu ne seras jamais à moi. »', 'https://images-na.ssl-images-amazon.com/images/I/411Zy3sfj2L._SX432_BO1,204,203,200_.jpg', TRUE, 8),
  (6, 'Le Verger, jeu de cartes',
    'Jeu coopératif amusant qui apprend aux jeunes enfants à travailler ensemble. En bois et en carton. Recommandé pour les enfants de 3 ans et plus', 'https://images-na.ssl-images-amazon.com/images/I/716H8Kl%2BQmL._AC_SL1500_.jpg', TRUE, 4),
  (7, 'La Fontaine raconte aux enfants',
    'Les sept fables les plus célèbres de Jean de La Fontaine, racontées comme des histoires aux plus petits. Pour découvrir les grands classiques à petits pas. Le Corbeau et le Renard, Le Lièvre et la Tortue, La Cigale et la Fourmi, La Grenouille qui se veut faire aussi grosse que le Boeuf, Le Loup et l Agneau, Le Renard et la Cigogne, Le Lion et le Rat. Un pan du patrimoine littéraire français : les Fables de La Fontaine.', 'https://images-na.ssl-images-amazon.com/images/I/51Wh6q7OsVL._SX380_BO1,204,203,200_.jpg', TRUE, 5),
  (8, 'La tour Eiffel se balade à Paris',
    'La tour Eiffel revient en album pour une promenade dans Paris ! Léa et Nino participent à une chasse au trésor dans Paris. Mais la ville est grande et les deux enfants ne savent pas où chercher... La tour Eiffel, qui a la bougeotte et des idées, va les accompagner à la découverte des lieux mythiques de la capitale.', 'https://images-na.ssl-images-amazon.com/images/I/51uutNbF+tL._SX417_BO1,204,203,200_.jpg', FALSE, 6);